[package]
name = "rig"
version = "0.1.0"
edition = "2021"

[lib]
name = "librig"
path = "src/librig.rs"

[[bin]]
name = "rig"
path = "src/rig.rs"

[dependencies]
bitfield = "*"
bincode = "1.3.3"
serde = {version = "*", features = ["derive"]}
rand = "*"
